services:
  dev:
    build:
      context: .
      target: development
    env_file: .env
    ports:
      - 3000:3000
    develop:
      watch:
        - action: sync
          path: ./website
          target: /app/website
        - action: sync
          path: ./serve.tsx
          target: /app/serve.tsx
  prod:
    build:
      context: .
      target: production
    ports:
      - 3000:3000
