name = "Jaffa Factory 2 (Replica)"
version = "The Factory Must Grow"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "060c274f42a7d2de0e1a15ed3cc8a56d51ab5efdda8dd6a4f2da71d769b90e1f"

[versions]
forge = "47.3.0"
minecraft = "1.20.1"
