name = "Jaffa Factory 2 (Replica)"
version = "The Factory Must Grow"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "72b5ecd0b20a3f5e2f76862ab0dc8283f1b7756a66817869cdfb8e7f2f3125e9"

[versions]
forge = "47.3.0"
minecraft = "1.20.1"
