name = "Jaffa Factory 2 (Replica)"
version = "The Factory Must Grow"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "cc910025783c4272272e2ce57a29c6f4c9994aafc9034c0a5d421e3abc27a344"

[versions]
forge = "47.3.0"
minecraft = "1.20.1"
