name = "Jaffa Factory 2 (Replica)"
version = "The Factory Must Grow"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "74f1fe61965defdaa5821137c5e1d28297c29a0ce4ffe67dd4487e287c021319"

[versions]
forge = "47.3.0"
minecraft = "1.20.1"
