name = "Jaffa Factory 2 (Replica)"
version = "The Factory Must Grow"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "feff993d89a34a8f1e38721c375d7738756db5c43855a6ce00478660847b090d"

[versions]
forge = "47.3.0"
minecraft = "1.20.1"
