name = "Jaffa Factory 2 (Replica)"
version = "The Factory Must Grow"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "572f40fc1dc53b566e5b4023ddfbfcd788621a94c767df75c8a9367e7440585c"

[versions]
forge = "47.3.0"
minecraft = "1.20.1"
