name = "Jaffa Factory 2 (Replica)"
version = "The Factory Must Grow"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "4279b2fcefefcaa2473e92e73dbfb692eee50cea15670cf96ea141cdde051663"

[versions]
forge = "47.3.0"
minecraft = "1.20.1"
