name = "Jaffa Factory 2 (Replica)"
version = "The Factory Must Grow"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "8d2f614cc26c7b573c036bd8b1b3114133adbb1aeba162ebef31621baf6b4d8d"

[versions]
forge = "47.3.0"
minecraft = "1.20.1"
