name = "Jaffa Factory 2 (Replica)"
version = "The Factory Must Grow"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "a64e9b503814b655165009e36203a1d87ed55a7c743ac15df8a777fa5351472e"

[versions]
forge = "47.3.0"
minecraft = "1.20.1"
