name = "Jaffa Factory 2 (Replica)"
version = "The Factory Must Grow"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "10acb84ab74b99b0689a45ad12db3fb698cb82af7c2b354ce3f13d9f08e8f486"

[versions]
forge = "47.3.0"
minecraft = "1.20.1"
