name = "Jaffa Factory 2 (Replica)"
version = "The Factory Must Grow"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "28d051316f4a81c4a77db300fb86a3cd093630f89b49cbe90ba9e95234a37302"

[versions]
forge = "47.3.0"
minecraft = "1.20.1"
