name = "Jaffa Factory 2 (Replica)"
version = "The Factory Must Grow"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "b5306b9a90935a6a49a57695b54ef999b550d24792ed04442bad0eb0cfb06e0e"

[versions]
forge = "47.3.0"
minecraft = "1.20.1"
