name = "Jaffa Factory 2 (Replica)"
version = "The Factory Must Grow"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "1b5cf73c863c7edfccacc5a651053b7d44323bd84bb0f0e3118d3f64a5639a7c"

[versions]
forge = "47.3.0"
minecraft = "1.20.1"
