name = "Jaffa Factory 2 (Replica)"
version = "The Factory Must Grow"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "149e17106bdf568d97f0f2e36353717f0e2b3d5b3d64fbb84b2aeaa22c83f978"

[versions]
forge = "47.3.0"
minecraft = "1.20.1"
