name = "Jaffa Factory 2 (Replica)"
version = "The Factory Must Grow"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "376e95e0eb6f43c6b2c75df8e43ae081bd38608c5a4cc8dd6692cfeb9fde04a9"

[versions]
forge = "47.3.0"
minecraft = "1.20.1"
