name = "Jaffa Factory 2 (Replica)"
version = "The Factory Must Grow"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "8b3c8647053c0b62e8c0f89d621b1d68629fb43c63a87035c0075d9cd5ef0184"

[versions]
forge = "47.3.0"
minecraft = "1.20.1"
