name = "Jaffa Factory 2 (Replica)"
version = "The Factory Must Grow"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "f39d8705f8c3d44aef39aa5b0ebd3673bbc82a9a99a21e9aedb61429cd7eda05"

[versions]
forge = "47.3.0"
minecraft = "1.20.1"
