name = "Jaffa Factory 2 (Replica)"
version = "The Factory Must Grow"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "c37002fefc9500184ed6b9a1d27c95618dcda1aa6519fce54282207371b69740"

[versions]
forge = "47.3.0"
minecraft = "1.20.1"
