name = "Jaffa Factory 2 (Replica)"
version = "The Factory Must Grow"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "d8b672f228e1fabc18c85a4cf0a933b791eb174f7c03ee5b0028a835faee218f"

[versions]
forge = "47.3.0"
minecraft = "1.20.1"
