name = "Jaffa Factory 2 (Replica)"
version = "The Factory Must Grow"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "de340e2b016cb32035ff75138b13d9c8c6342a6310de5b903ec1fbd3bb64995b"

[versions]
forge = "47.3.0"
minecraft = "1.20.1"
