name = "Jaffa Factory 2 (Replica)"
version = "The Factory Must Grow"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "18ae3242b7ab2149ae79b2c164ed2bf9acbff921fe7ef339b1af17b8cd54b775"

[versions]
forge = "47.3.0"
minecraft = "1.20.1"
